Repository Samsamhada/Giwazip-Client-App, pull requests merged in 2023-02, with the labels that each got.

#34 [Design] AS기간 셀 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/ASCell.swift
  GiwazipClient/Views/HistoryViewController.swift
Labels: design

#31 [Feature] 썸네일 클릭 시 동작
  GiwazipClient/Cells/PostCell.swift
  GiwazipClient/Supports/BaseViewController.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/PostViewController.swift
  GiwazipClient/Views/PostingPhotoViewController.swift
Labels: feature

#35 [Feature] 문의내역 작성하기 버튼 동작
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/ASCell.swift
  GiwazipClient/Cells/HistoryCell.swift
  GiwazipClient/Cells/PostDateHeader.swift
  GiwazipClient/Cells/ProgressHeader.swift
  GiwazipClient/Coordinators/AppCoordinator.swift
  GiwazipClient/Coordinators/MainCoordinator.swift
  GiwazipClient/Coordinators/PostingPhotoCoordinator.swift
  GiwazipClient/Coordinators/SegmentCoordinator.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/PostingPhotoViewController.swift
  GiwazipClient/Views/SegmentViewController.swift
Labels: feature

#37 [Design] 문의내역 테스트 뷰 디자인 및 기능
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Views/PostingTextViewController.swift
Labels: design, feature

#40 [Design] 진행률 셀 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/ProgressCell.swift
  GiwazipClient/Cells/WaveView.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/SegmentViewController.swift
Labels: design

#44 [Docs] Add APIEnvironment ignore
  .gitignore
Labels: documentation

#43 [Design] 환경설정 뷰 레이아웃 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Views/SettingViewController.swift
Labels: design

#48 [Chore] 리터럴 디렉터리 및 파일 생성
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/ASCell.swift
  GiwazipClient/Extensions+/Alert+.swift
  GiwazipClient/Literals/ColorLiteral.swift
  GiwazipClient/Literals/TextLiteral.swift
  GiwazipClient/Views/EnterViewController.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/PostViewController.swift
  GiwazipClient/Views/PostingPhotoViewController.swift
  GiwazipClient/Views/PostingTextViewController.swift
  GiwazipClient/Views/SegmentViewController.swift
  GiwazipClient/Views/SettingViewController.swift
  GiwazipClient/Views/SplashViewController.swift
Labels: chore

#45 [Feature] NetworkManager(Get) + Model
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Models/Model.swift
  GiwazipClient/Models/Models.swift
  GiwazipClient/Models/NetworkResult.swift
  GiwazipClient/Resources/Assets.xcassets/cat2.imageset/Contents.json
  GiwazipClient/Resources/Assets.xcassets/cat2.imageset/IMG_7133.HEIC
  GiwazipClient/SceneDelegate.swift
  GiwazipClient/ViewModels/NetworkManager.swift
Labels: feature

#52 [Feature] 환경설정 뷰에서 일부 리스트 클릭시 기능 추가
  GiwazipClient/Literals/TextLiteral.swift
  GiwazipClient/Views/SettingViewController.swift
Labels: feature
