Repository Samsamhada/Giwazip-Client-App, pull requests merged in 2023-03, with the labels that each got.

#50 [Fix] 뷰 스크롤시 진행률이 첫번째로 돌아가는 문제 외 1개 문제 해결
  GiwazipClient/Views/HistoryViewController.swift
Labels: fix

#53 [Feature] NetworkManager (Put, Post) 기능 추가
  GiwazipClient/Models/NetworkResult.swift
  GiwazipClient/ViewModels/NetworkManager.swift
Labels: feature

#55 [Docs] APIKey 비공개처리
  .gitignore
Labels: documentation

#54 [Feature] NetworkManager 게시물 post 및 코드 스타일 수정
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Models/NetworkResult.swift
  GiwazipClient/ViewModels/NetworkManager.swift
Labels: feature

#57 [Design] 환경설정 뷰 카피라이트 추가 및 개발자 정보 뷰 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/SettingFooter.swift
  GiwazipClient/Literals/ImageLiteral.swift
  GiwazipClient/Literals/TextLiteral.swift
  GiwazipClient/Resources/Assets.xcassets/GitHubLogo.imageset/Contents.json
  GiwazipClient/Resources/Assets.xcassets/GitHubLogo.imageset/github-logo.png
  GiwazipClient/Views/DeveloperViewController.swift
  GiwazipClient/Views/SettingViewController.swift
Labels: design

#60 [Design] 공지사항 뷰 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Models/Models.swift
  GiwazipClient/Views/NoticeViewController.swift
Labels: design

#70 [Feature] 히스토리 뷰 데이터 연동
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/ASCell.swift
  GiwazipClient/Cells/Cell.swift
  GiwazipClient/Cells/HistoryCell.swift
  GiwazipClient/Cells/PostDateHeader.swift
  GiwazipClient/Cells/ProgressCell.swift
  GiwazipClient/Cells/ProgressHeader.swift
  GiwazipClient/Extensions+/Extension+.swift
  GiwazipClient/Extensions+/LineDashPattern+.swift
  GiwazipClient/Literals/TextLiteral.swift
  GiwazipClient/Models/Models.swift
  GiwazipClient/Supports/BaseViewController.swift
  GiwazipClient/UIComponents/ASView.swift
  GiwazipClient/UIComponents/WaveView.swift
  GiwazipClient/ViewModels/NetworkManager.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/SegmentViewController.swift
Labels: chore, design, feature, fix

#71 [Chore] Coordinator Pattern 적용
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/PostCell.swift
  GiwazipClient/Coordinators/AppCoordinator.swift
  GiwazipClient/Coordinators/DeveloperCoordinator.swift
  GiwazipClient/Coordinators/EnterCoordinator.swift
  GiwazipClient/Coordinators/HistoryCoordinator.swift
  GiwazipClient/Coordinators/LicenseCoordinator.swift
  GiwazipClient/Coordinators/MainCoordinator.swift
  GiwazipClient/Coordinators/NoticeCoordinator.swift
  GiwazipClient/Coordinators/PostCoordinator.swift
  GiwazipClient/Coordinators/PostImageCoordinator.swift
  GiwazipClient/Coordinators/PostingCoordinator.swift
  GiwazipClient/Coordinators/PostingPhotoCoordinator.swift
  GiwazipClient/Coordinators/PostingTextCoordinator.swift
  GiwazipClient/Coordinators/SegmentCoordinator.swift
  GiwazipClient/Coordinators/SettingCoordinator.swift
  GiwazipClient/Coordinators/SplashCoordinator.swift
  GiwazipClient/Coordinators/SubCoordinator.swift
  GiwazipClient/Extensions+/UIBackBarButton+.swift
  GiwazipClient/Literals/TextLiteral.swift
  GiwazipClient/Views/DeveloperViewController.swift
  GiwazipClient/Views/EnterViewController.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/LicenseViewController.swift
  GiwazipClient/Views/MainViewController.swift
  GiwazipClient/Views/NoticeViewController.swift
  GiwazipClient/Views/PostImageViewController.swift
  GiwazipClient/Views/PostViewController.swift
  GiwazipClient/Views/PostingPhotoViewController.swift
  GiwazipClient/Views/PostingTextViewController.swift
  GiwazipClient/Views/SegmentViewController.swift
  GiwazipClient/Views/SettingViewController.swift
  GiwazipClient/Views/SplashViewController.swift
  GiwazipClient/Views/SubViewController.swift
Labels: chore, design, remove
