Repository Samsamhada/Giwazip-Client-App, pull requests merged in 2023-01, with the labels that each got.

#7 [Chore] 프로젝트 구조 변경 및 초기 세팅
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient.xcworkspace/contents.xcworkspacedata
  GiwazipClient.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GiwazipClient/AppDelegate.swift
  GiwazipClient/AutoLayout+.swift
  GiwazipClient/Cells/Cell.swift
  GiwazipClient/Coordinators/AppCoordinator.swift
  GiwazipClient/Coordinators/MainCoordinator.swift
  GiwazipClient/Coordinators/SubCoordinator.swift
  GiwazipClient/Extensions+/Extension+.swift
  GiwazipClient/JoinViewController.swift
  GiwazipClient/Models/Model.swift
  GiwazipClient/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  GiwazipClient/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  GiwazipClient/Resources/Assets.xcassets/Contents.json
  GiwazipClient/Resources/Info.plist
  GiwazipClient/SceneDelegate.swift
  GiwazipClient/Services/Service.swift
  GiwazipClient/Supports/BaseCoordinator.swift
  GiwazipClient/Supports/BaseViewController.swift
  GiwazipClient/ViewController.swift
  GiwazipClient/ViewModels/ViewModel.swift
  GiwazipClient/Views/Base.lproj/LaunchScreen.storyboard
  GiwazipClient/Views/MainViewController.swift
  GiwazipClient/Views/SubViewController.swift
  GiwazipClient/Views/ko.lproj/LaunchScreen.strings
  Podfile
  Podfile.lock
Labels: chore

#10 [Design] 고객용 어플 입장 화면 레이아웃 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Views/SplashViewController.swift
Labels: design

#15 [Design] EnterView 레이아웃 1차 PR
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Views/EnterViewController.swift
Labels: wip

#13 [Design] HistoryView 레이아웃
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/HistoryCell.swift
  GiwazipClient/Cells/PostDateCell.swift
  GiwazipClient/Cells/ProgressHeader.swift
  GiwazipClient/SceneDelegate.swift
  GiwazipClient/Views/HistoryViewController.swift
  GiwazipClient/Views/SegmentViewController.swift
Labels: design

#21 [Design] 문의내역 작성하기(사진) 레이아웃
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Cells/PostingPhotoCell.swift
  GiwazipClient/Views/PostingPhotoViewController.swift
Labels: design

#17 [Design] enterview layout 최종 완료
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Extensions+/Alert+.swift
  GiwazipClient/Extensions+/HideKeyboard+.swift
  GiwazipClient/Supports/BaseViewController.swift
  GiwazipClient/Views/EnterViewController.swift
Labels: design

#24 [Style] Enterviewcontroller 스냅킷 코드 스타일 변경
  GiwazipClient/Views/EnterViewController.swift
Labels: style

#25 [Feature] 문의내역 사진 업로드 셀 기능 추가
  GiwazipClient/Cells/PostingPhotoCell.swift
  GiwazipClient/Extensions+/Alert+.swift
  GiwazipClient/Views/PostingPhotoViewController.swift
Labels: design, feature

#26 [Feature] 사진 확대 축소 제스쳐 기능 추가
  GiwazipClient.xcodeproj/project.pbxproj
  GiwazipClient/Resources/Assets.xcassets/cat.imageset/Contents.json
  GiwazipClient/Resources/Assets.xcassets/cat.imageset/IMG_6511.heic
  GiwazipClient/Resources/Assets.xcassets/cat2.imageset/Contents.json
  GiwazipClient/Resources/Assets.xcassets/cat2.imageset/IMG_7133.HEIC
  GiwazipClient/Views/PostImageViewController.swift
Labels: feature
